version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8000:80"
        depends_on:
            - app
        container_name: mamr_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        links:
            - db
        container_name: mamr_app

    db:
        image: mysql:latest
        restart: always
        networks:
            default:
        volumes:
            - ./tmp/db/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: mamr-articles
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: mamr_db

